# HMAC-SHA3-256 can use a 136 byte key.
# 136*(26×2+10) ≃ 8432 bits of random
apiVersion: v1
kind: Secret
metadata:
  name: clacheless-dc
type: Opaque
data:
  {{- $existing_secret := (lookup "v1" "Secret" .Release.Namespace "clacheless-dc") }}
  {{- if not $existing_secret }}
  # Generate secrets
  current: {{ randAlphaNum 136 | b64enc  | b64enc}}
  {{ else }}
  # Reuse secret
  current: {{ index $existing_secret.data "current" }}
  {{ end }}
