apiVersion: v1
kind: Service
metadata:
  name: clacheless
  labels:
    app.kubernetes.io/name: clacheless
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: clacheless
    app.kubernetes.io/instance: "{{ .Release.Name }}"
