/*
    Copyright 2025 MydriaTech AB

    Licensed under the Apache License 2.0 with Free world makers exception
    1.0.0 (the "License"); you may not use this file except in compliance with
    the License. You should have obtained a copy of the License with the source
    or binary distribution in file named

        LICENSE-Apache-2.0-with-FWM-Exception-1.0.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![doc = include_str!("../README.md")]

mod clacheless_error;
mod distributed_cache;
pub(crate) mod proto {
    //! Includes gRPC code generated by `build.rs`

    pub mod stateshare {
        //! gRPC package for sharing a cache over network.

        tonic::include_proto!("stateshare");
    }
}
pub(crate) mod time;
pub mod util;

pub use self::distributed_cache::DistributedCache;
pub use clacheless_error::*;
